title: Kapil Vaishnav 
logo: "kapil vaishnav.jpg?raw=true" 
description: > 
      Become Good Engineer
  <br><br>
  <a href="mailto:kvaishnav408@gmail.com">kvaishnav408@gmail.com</a> 
  <br>
  <a href="https://twitter.com/kapil__vaishnav">Twitter Account</a> 
  <br>
   <a href="https://www.linkedin.com/in/kapil-vaishnav-09a3a71ba/">LinkedIn Profile</a> 
theme: jekyll-theme-minimal
